MyDjangoRestApi/urls.py
from django.conf.urls import patterns, include, url
from MyViewApp import views
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^api/', include('MyTaskData.urls')),
    url(r'^admin/', include(admin.site.urls)),
     url(r'^myview/',views.myView),
      url(r'^myPanel/',include('MyViewApp.urls')),
)

MyTaskData/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns(
    'MyTaskData.views',
    url(r'^tasks/$', 'task_list', name='task_list'),
    url(r'^tasks/(?P<pk>[0-9]+)$', 'task_detail', name='task_detail'),

)

MyViewApp/urls.py
from django.conf.urls import patterns, url
from MyViewApp import views

urlpatterns = patterns(
    '',
    url(r'^$',views.myPanel,name="myPanel"),
    url(r'^deleteme/(?P<id>\d+)/$',views.deleteme),
    url(r'^editme/(?P<id>\d+)/$', views.editme),
 url(r'^addData/$', views.addme),
)

MyTaskData/models.py
from django.db import models
from django.utils import timezone
class TaskData(models.Model):
    fields = models.ForeignKey('MyFields',null=True,blank=True)
    data = models.ForeignKey('MyData',null=True,blank=True)



class MyFields(models.Model):
    did = models.CharField('id',unique=True, max_length=128,null=True,blank=True)
    label=models.CharField('id',unique=True, max_length=128,null=True,blank=True)
    type=models.CharField('id',unique=True, max_length=128,null=True,blank=True)


#Main Model In Question Above Models are Miscelleneous
class MyData(models.Model):
    device_name=models.CharField('device_name' ,max_length=128,null=True,blank=True)
    magnification=models.CharField('magnification', max_length=128,null=True,blank=True)
    field_of_view=models.CharField('field_of_view', max_length=128,null=True,blank=True)
    range=models.CharField('range', max_length=128,null=True,blank=True)
    created_date=models.DateField('created_date',default=timezone.now())

MyTaskData/views.py
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import permissions
from django.http import HttpResponse
from .models import MyData
from .serializers import TaskSerializer

permission_classes = (permissions.IsAuthenticatedOrReadOnly,)

@api_view(['GET', 'POST'])
def task_list(request):

    """
    List all tasks, or create a new task.
    """
    if request.method == 'GET':
        tasks = MyData.objects.all()
        serializer = TaskSerializer(tasks, many=True)
        return Response(serializer.data)

    elif request.method == 'POST':
        serializer = TaskSerializer(data=request.DATA)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        else:
            return Response(
                serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['GET', 'PUT', 'DELETE'])
def task_detail(request, pk):
    """
    Get, udpate, or delete a specific task
    """
    try:
        task = MyData.objects.get(pk=pk)
    except MyData.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'GET':
        serializer = TaskSerializer(task)
        return Response(serializer.data)

    elif request.method == 'PUT':
        serializer = TaskSerializer(task, data=request.DATA)
        print(serializer)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        else:
            return Response(
                serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    elif request.method == 'DELETE':
        task.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

MyViewApp/views.py
from MyTaskData.models import MyData
from pure_pagination import Paginator,PageNotAnInteger
from django.template.context import RequestContext
from django.conf import settings
from django.http import HttpResponseRedirect,HttpResponse
from django.shortcuts import render_to_response
from django.core.urlresolvers import reverse, reverse_lazy
from MyTaskData.models import MyData
from .utility import myUtiLity
#This is the view used for filtering
def myView(request):
    context = RequestContext(request)
    #pagination Logic
    page=myUtiLity.my_page(request)
    if request.method == 'GET':
       mydata=MyData.objects.all()
       p = Paginator(mydata,settings.PER_PAGE_NUMBER, request=request)
       myList = p.page(page)
       return render_to_response(
           'myview/myView.html', {'myData':myList,'all_records':1}, context)
    elif request.method == 'POST':
       search_text = str(request.POST.get('search_text','')).strip()
       mydata=MyData.objects.filter(device_name__icontains=search_text)
       print(mydata)
       return render_to_response(
           'myview/myView.html',{'myData':mydata,'all_records':0}, context)

#This is the admin Panel
def myPanel(request):
    context = RequestContext(request)
    page=myUtiLity.my_page(request)
    if request.method == 'GET':
       my_data=MyData.objects.all()
       myList=[]
       #This Part will Put recrently added article above at top of list
       for field in my_data[::-1]:
           myList.append(field)
       p = Paginator(myList,settings.PER_PAGE_NUMBER, request=request)
       myList = p.page(page)
       return render_to_response(
           'myview/myPanel.html', {'myData':myList,'all_records':1}, context)

#This is the delete me function
def deleteme(request,id):
    mydata=MyData.objects.get(pk=id)
    mydata.delete()
    return HttpResponseRedirect(reverse('myPanel',args=[]))

#This is the edit me function
def editme(request,id):
    context=RequestContext(request)
    if request.method=='POST':
       device_name=request.POST.get("device_name","")
       magnification=myUtiLity.form_field_value(request,"magnification")
       range=myUtiLity.form_field_value(request,"range")
       field_of_view=myUtiLity.form_field_value(request,"field_of_view")
       mydata=MyData.objects.get(pk=id)

       MyData(pk=mydata.pk,device_name=device_name,magnification=magnification,range=range,field_of_view=field_of_view).save()

       return HttpResponseRedirect(reverse('myPanel',args=[]))
    elif request.method=='GET':
       try:
           mydata=MyData.objects.get(pk=id)
       except:
           return HttpResponse('Sorrry Id Not Available')
       return render_to_response(
           'myview/editData.html',{"mydata":mydata}, context)

#This is add Data method
def addme(request):
    context=RequestContext(request)
    if request.method=='POST':
       device_name=request.POST.get("device_name","")
       magnification=myUtiLity.form_field_value(request,"magnification")
       range=myUtiLity.form_field_value(request,"range")
       field_of_view=myUtiLity.form_field_value(request,"field_of_view")

       MyData(device_name=device_name,magnification=magnification,range=range,field_of_view=field_of_view).save()
       return HttpResponseRedirect(reverse('myPanel',args=[]))
    elif request.method=='GET':
       return render_to_response(
           'myview/addData.html',{}, context)

pure_pagination/templates/pure_pagination/pagination.html
{% load i18n %}
<div class="pagination">
    {% if page_obj.has_previous %}
        <a href="?{{ page_obj.previous_page_number.querystring }}" class="prev">&lsaquo;&lsaquo; {% trans "previous" %}</a>
    {% else %}
        <span class="disabled prev">&lsaquo;&lsaquo; {% trans "previous" %}</span>
    {% endif %}
 {% for page in page_obj.pages %}
        {% if page %}
            {% ifequal page page_obj.number %}
                <span class="current page">{{ page }}</span>
            {% else %}
                <a href="?page={{ page }}" class="page">{{ page }}</a>
            {% endifequal %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
        <a href="?{{ page_obj.next_page_number.querystring }}" class="next">{% trans "next" %} &rsaquo;&rsaquo;</a>
    {% else %}
        <span class="disabled next">{% trans "next" %} &rsaquo;&rsaquo;</span>
    {% endif %}
</div>

templates/myview/addData.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Add Data</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
   <script>
    $(document).ready(function()
    {

    $('#id_submit').click(function()
    {

    if ($('#id_device_name').val().length<=0)
    {
    alert('Required Field');
    return false;
    }
    });
   } );
   </script>
</head>
<body>

<div style="margin-left:350px;margin-top:150px;border: 1px solid;width:30%;padding:10px;">
    <span style="margin-left: 120px;font-size: 20px;text-decoration: underline">Add Data</span>
    <br/>
    <br/>
     <br/>
<form  action="/myPanel/addData/" method="post">
Device Name : &nbsp;&nbsp;
<input type="text" name="device_name" id="id_device_name"/>
<br/>
<br/>
    Magnification : &nbsp;&nbsp;
<input type="text" name="magnification"/>
<br/><br/>
    Range : &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<input type="text" name="range"/>
<br/><br/>
    Field Of View : &nbsp;&nbsp;
<input type="text" name="field_of_view"/>
<br/><br/>

{% csrf_token %}
 <input style="margin-left: 115px;"type="submit" id="id_submit" value="Add Data"></form>

</div>

</div>
</body>
</html>

templates/myview/editData.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Edit Data</title>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
   <script>
    $(document).ready(function()
    {

    $('#id_submit').click(function()
    {

    if ($('#id_device_name').val().length<=0)
    {
    alert('Required Field');
    return false;
    }
    });
   } );
   </script>
</head>
<body>

<div style="margin-left:350px;margin-top:150px;border: 1px solid;width:30%;padding:10px;">
    <span style="margin-left: 120px;font-size: 20px;text-decoration: underline">Edit  Data</span>
    <br/>
    <br/>
     <br/>
<form  action="/myPanel/editme/{{ mydata.pk }}/" method="post">
Device Name : &nbsp;&nbsp;
<input type="text" id="id_device_name" name="device_name" value="{{ mydata.device_name }}"/>
<br/>
<br/>
    Magnification : &nbsp;&nbsp;
<input type="text" name="magnification"  value="{{ mydata.magnification }}"/>
<br/><br/>
    Range : &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<input type="text" name="range"  value="{{ mydata.range }}"/>
<br/><br/>
    Field Of View : &nbsp;&nbsp;
<input type="text" name="field_of_view"  value="{{ mydata.field_of_view }}"/>
<br/><br/>


 <input id="id_submit" style="margin-left: 115px;"type="submit" value="Edit Data">
{% csrf_token %}</form>
</div>

</div>
</body>
</html>

templates/myview/myPanel.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<div style="margin-left:300px;margin-top:150px">
<span style=""><a href="/myPanel/addData/">Add Data</a></span>
    <div style="margin-top: 10px">

<table border="1">
<tr>
     <th>Edit</th>
      <th>Delete</th>
   <th>Device Name</th>
       <th>Magnification</th>
     <th>Field Of View</th>

 <th>Range</th>

</tr>


    {% if myData.object_list %}
{% for field in myData.object_list %}

  <tr>
   <td><a href="/myPanel/editme/{{ field.pk }}/">Edit</a></td>
       <td><a href="/myPanel/deleteme/{{ field.pk}}/">Delete</a></td>
  <td>{{ field.device_name }}</td>
  <td>{{ field.magnification }}</td>
  <td>{{ field.field_of_view }}</td>
  <td>{{ field.range }}</td>
</tr>     {% endfor %}
    {% else %}
    <tr>Sorry No data</tr>




    {% endif %}




</table>
    </div>
{% if all_records == 1%}
<div id="pagination">
 {{ myData.render }}
</div>
{% endif %}
</div>
</body>
</html>

templates/myview/myView.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<div style="margin-left:300px;margin-top:150px">
<form  action="/myview/" method="post">
Device Name : &nbsp;&nbsp;
<input type="text" name="search_text"/>
    <input type="submit" value="Search">
    {% csrf_token %}
</form>
    <div style="margin-top: 10px">

<table border="1">
<tr>
     <th>Index</th>
   <th>Device Name</th>
       <th>Magnification</th>
     <th>Field Of View</th>

 <th>Range</th>

</tr>
{% if all_records == 1%}

    {% if myData.object_list %}
{% for field in myData.object_list %}

  <tr>
   <td>{{ field.pk }}</td>
  <td>{{ field.device_name }}</td>
  <td>{{ field.magnification }}</td>
  <td>{{ field.field_of_view }}</td>
  <td>{{ field.range }}</td>
</tr>     {% endfor %}
    {% else %}
    <tr>Sorry No data</tr>




    {% endif %}
    {% else %}
    {% if myData%}
{% for field in myData %}

  <tr>
   <td>{{ field.pk }}</td>
  <td>{{ field.device_name }}</td>
  <td>{{ field.magnification }}</td>
  <td>{{ field.field_of_view }}</td>
  <td>{{ field.range }}</td>
</tr>     {% endfor %}
    {% else %}
      <tr>Sorry No Data</tr>
    {% endif %}

{% endif %}
</table>
    </div>
{% if all_records == 1%}
<div id="pagination">
 {{ myData.render }}
</div>
{% endif %}
</div>
</body>
</html>